maintainer       "Trotter Cashion"
maintainer_email "cashion@gmail.com"
license          "MIT"
description      "Installs/Configures chloe"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.0.1"
depends          "erlang"
depends          "git"
supports         "ubuntu"
supports         "debian"
